tap "adoptopenjdk/openjdk"
tap "clementtsang/bottom"
tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "ms-jpq/sad"
tap "pulumi/tap"
tap "tavianator/tap"
tap "wez/wezterm"
tap "withgraphite/tap"
brew "act"
brew "adr-tools"
brew "jpeg-turbo"
brew "openssl@3"
brew "aws-sam-cli"
brew "awscli"
brew "bandwhich"
brew "bash"
brew "bat"
brew "black"
brew "bottom"
brew "broot"
brew "fontconfig"
brew "glib"
brew "chezmoi"
brew "clang-format"
brew "cmake"
brew "curl"
brew "deno"
brew "pinentry"
brew "gnupg"
brew "poppler"
brew "diff-pdf"
brew "diff-so-fancy"
brew "difftastic"
brew "dive"
brew "docker"
brew "dust"
brew "fd"
brew "gcc"
brew "harfbuzz"
brew "openblas"
brew "ffmpeg"
brew "fish"
brew "fnm"
brew "fontforge"
brew "node"
brew "fx"
brew "fzf"
brew "geos"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "git-quick-stats"
brew "glow"
brew "gmailctl"
brew "go"
brew "graphviz"
brew "helix"
brew "helm"
brew "hexyl"
brew "hey"
brew "highlight"
brew "howdoi"
brew "htop"
brew "http-server"
brew "httpie"
brew "imagemagick"
brew "ipython"
brew "isort"
brew "jj"
brew "jq"
brew "lazygit"
brew "ldns"
brew "legit"
brew "leveldb"
brew "lf"
brew "libmagic"
brew "llm"
brew "locust"
brew "luajit"
brew "lychee"
brew "mackup"
brew "mailhog"
brew "mas"
brew "mongosh"
brew "mtr"
brew "protobuf@21"
brew "mysql", restart_service: true
brew "mysql-client"
brew "neovim"
brew "nmap"
brew "node@18"
brew "nushell"
brew "openssh"
brew "parquet-cli"
brew "pgloader"
brew "pinentry-mac"
brew "pipx"
brew "pkg-config"
brew "pnpm"
brew "poetry"
brew "postgresql@16", restart_service: true
brew "pre-commit"
brew "prettier"
brew "procs"
brew "pulumi"
brew "pyenv"
brew "pygments", link: false
brew "redis"
brew "ripgrep"
brew "ruby"
brew "ruff"
brew "rustup-init"
brew "scc"
brew "sd"
brew "shellcheck"
brew "starship"
brew "stylua"
brew "svgo"
brew "teensy_loader_cli"
brew "tokei"
brew "trash"
brew "tree"
brew "universal-ctags"
brew "uv"
brew "vivid"
brew "wakatime-cli"
brew "watchman"
brew "wget"
brew "yarn"
brew "yt-dlp"
brew "zbar"
brew "zellij"
brew "zenith"
brew "zoxide"
brew "heroku/brew/heroku"
brew "ms-jpq/sad/sad"
brew "tavianator/tap/bfs"
brew "withgraphite/tap/graphite"
cask "1password"
cask "1password-cli"
cask "battery"
cask "cursorsense"
cask "darktable"
cask "dbgate"
cask "drawio"
cask "firefox"
cask "fly"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-input"
cask "font-inter"
cask "font-monaspace"
cask "font-monofur-for-powerline"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-drive"
cask "graphql-playground"
cask "hex-fiend"
cask "imageoptim"
cask "inkscape"
cask "istat-menus"
cask "krita"
cask "lapce"
cask "linear-linear"
cask "mysqlworkbench"
cask "notion"
cask "obsidian"
cask "pdf-expert"
cask "postman"
cask "raindropio"
cask "raycast"
cask "slack"
cask "suspicious-package"
cask "transmit"
cask "wezterm-nightly"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Apple Configurator", id: 1037126344
mas "Cardhop", id: 1290358394
mas "DaisyDisk", id: 411643860
mas "Developer", id: 640199958
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "HazeOver", id: 430798174
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "MindNode", id: 1289197285
mas "Moom", id: 419330170
mas "mymind", id: 1532801185
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Poolsuite FM", id: 1514817810
mas "Save to Raindrop.io", id: 1549370672
mas "Tailscale", id: 1475387142
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835
