tap "adoptopenjdk/openjdk"
tap "clementtsang/bottom"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "osx-cross/avr"
tap "px4/px4"
tap "superfly/tap"
tap "wez/wezterm"
brew "act"
brew "adr-tools"
brew "avrdude"
brew "awscli"
brew "bat"
brew "black"
brew "bottom"
brew "pkg-config"
brew "broot"
brew "fontconfig"
brew "glib"
brew "clang-format"
brew "cmake"
brew "curl"
brew "datasette"
brew "dcraw"
brew "dfu-programmer"
brew "dfu-util"
brew "diff-so-fancy"
brew "dog"
brew "dust"
brew "exa"
brew "fd"
brew "fdupes"
brew "harfbuzz"
brew "ffmpeg"
brew "fish"
brew "fontforge"
brew "fzf"
brew "gcc"
brew "geos"
brew "gh"
brew "git"
brew "git-quick-stats"
brew "pinentry"
brew "gnupg"
brew "go"
brew "graphviz"
brew "hexyl"
brew "highlight"
brew "howdoi"
brew "htop"
brew "httpie"
brew "idris"
brew "imagemagick"
brew "imageoptim-cli"
brew "ipython"
brew "jq"
brew "ldns"
brew "legit"
brew "libmagic"
brew "lychee"
brew "mackup"
brew "mailhog"
brew "mas"
brew "micropython"
brew "mitmproxy"
brew "qt"
brew "mkvtoolnix"
brew "mongosh"
brew "neovim"
brew "node"
brew "openblas"
brew "openssh"
brew "pinentry-mac"
brew "pipx"
brew "poppler"
brew "postgresql", restart_service: true
brew "postgresql@13"
brew "procs"
brew "pyenv"
brew "pygments"
brew "redis"
brew "ripgrep"
brew "rustup-init"
brew "scc"
brew "sd"
brew "sloccount"
brew "spatialite-tools"
brew "starship"
brew "stylua"
brew "teensy_loader_cli"
brew "tokei"
brew "trash"
brew "tree"
brew "universal-ctags"
brew "wakatime-cli"
brew "wget"
brew "xml2"
brew "yarn"
brew "youtube-dl"
brew "zenith"
brew "zoxide"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
brew "osx-cross/avr/avr-gcc@8", link: true
brew "px4/px4/gcc-arm-none-eabi"
brew "superfly/tap/flyctl"
cask "adoptopenjdk8"
cask "capture-one"
cask "cursorsense"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-input"
cask "font-inter"
cask "font-monofur-for-powerline"
cask "google-chrome"
cask "google-chrome-canary", args: { appdir: "/Applications" }
cask "google-drive"
cask "hex-fiend"
cask "imageoptim"
cask "inkscape"
cask "istat-menus"
cask "iterm2"
cask "kitty"
cask "launchbar"
cask "openrefine"
cask "pdf-expert"
cask "poedit"
cask "screenflow"
cask "slack"
cask "sourcetree"
cask "steam"
cask "transmit"
cask "twist"
cask "visual-studio-code"
cask "vlc"
cask "wezterm-nightly"
cask "wireshark"
cask "zoom"
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "iMovie", id: 408981434
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "Moom", id: 419330170
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Screegle", id: 1591051659
mas "Sweet Home 3D", id: 669289700
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
